spring.application.name=ms-ventas
server.port=8083


spring.datasource.url=jdbc:mysql://98.89.176.25:3306/db_sales
spring.datasource.username=admin
spring.datasource.password=modeltoys
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect